---
- name: Configure SSH and create a new user
  hosts: all
  become: yes  # This is to become root on the remote host
  gather_facts: no
  vars_files:
    - vault.yaml

  tasks:

    - name: Checking the Ubuntu version
      command: cat /etc/lsb-release
      register: lsb_release_output
      changed_when: false
      failed_when: "'Ubuntu 22.04.3 LTS' not in lsb_release_output.stdout"

    - name: Create Cloudru User
      user:
        name: "{{ cloudru_user }}"
        password: "{{ cloudru_password | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes
      become_user: root

    - name: Allows ssh key authentication on the host
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^(PubkeyAuthentication)'
        line: 'PubkeyAuthentication yes'
        state: present
      notify:
        - restart ssh

    - name: Disable SSH login for root user
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^(PermitRootLogin|PermitRootLogin without-password)'
        line: 'PermitRootLogin no'
        state: present
      notify:
        - restart ssh

    - name: Copies the public key for the cloudru user
      become: yes
      authorized_key:
        user: cloudru
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfrfE0OluoNHb5dOpV4RpWmVXvMBWc17kaM7DDjCm7romNQMDX95i5Fc67Q3c47pvrm/qi/ZqsCeqNdLl5+VV41rVz701Pj/UUr2FZpIm80Ur0iM1DFy81GKo/lS1INopqdd4KvUnM2d8yqfJSm9m5Cq7AM9S0mqObuMayfqNR4YcOlm9fnEMqhrSWbBVvdghPNiBzs7T9RzEq/0w8rs743tCF7MICv72fdgYadrGlxFsFWSujwZXQLI4VUSxKirJBCUgfR0u84gZK/wUzJ4EPqMichniTf24AsvidozUHWMDmQ+pUaBTyxjD5egi8LcV0EHH4feHwzacA2gyGbOtFK3wpa/dgE1yvPTkPKnccIXKnbel0mfxfsBVkclc5/DnczmrdaGrX5DCrQbI+HO4lhr4KzAm/pw6qfLcw8KjCdVKsnCRXykdat8KUwNAeolknRWdKDqdsbyXBj+ePMTlMR8YmoBj9znYWwOnAAyu56utiteL0oq9YPkb7ZGF5ZOE=
        state: present

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted
